Fix tests: Use @pytest_asyncio.fixture instead of @pytest.fixture
This fixes the exception:

    AttributeError: 'async_generator' object has no attribute [...]